### ISSUE TITLE
Fix whatsapp logo

### ISSUE THREAD

**Issue by rhnvrm** [snu-breeze/breeze-landing-2016#15]
It's not appearing since no style is available for before:

![screenshot from 2016-07-15 00-29-15](https://cloud.githubusercontent.com/assets/952036/16851905/4315d4fa-4a23-11e6-9e44-e79fb6459b12.png)

@harshitbudhraja

**Comment by ghost** [comment]
By looking at the font-awesome css stylesheet, I got the access number for whatsapp's icon. But even after using it, does'nt work....
`
fa-whatsapp:before {
    content: "\f232";
}
`
@rhnvrm ....Should I look for and try some other way ?

**Comment by rhnvrm** [comment]
@harshitbudhraja There are two duplicate rules in the file, did you change them both?
