### ISSUE TITLE
Artist names collide on small screen sizes

### ISSUE THREAD

**Issue by rhnvrm** [snu-breeze/breeze-landing-2016#23]
by @anuragsai97 

![photo_2016-07-18_21-42-21](https://cloud.githubusercontent.com/assets/952036/16921808/ae35bab0-4d30-11e6-9e20-93afe9556125.jpg)

**Comment by ghost** [comment]
We can fix that just by reducing the font size when the screen goes around  800px wide right ?
@rhnvrm

**Comment by rhnvrm** [comment]
iirc, it will still bug on xs screens even with changing font sizes. Better
to change xs layout to 1-3-3 from 1-2-4.

Take liberty and decide what is best, post screenshots first and we can
discuss how to resolve this in the best way

Sincerely,
Rohan Verma
hello@rohanverma.net

**Comment by rhnvrm** [comment]
@harshitbudhraja any update on the progress?

**Comment by ghost** [comment]
@rhnvrm, I just started working on it....Changed to 1-3-3....It fixes the problem
Should I create a PR ?

**Comment by rhnvrm** [comment]
@harshitbudhraja yes with screenshots if possible using chrome dev tools

**Comment by ghost** [comment]
Think this should be closed now ! What say @rhnvrm ?
