### ISSUE TITLE
Update photos of Memories Section

### ISSUE THREAD

**Issue by rhnvrm** [snu-breeze/breeze-landing-2016#7]
1. Download best 8 photos from https://www.flickr.com/photos/kondapivskrishnaprasanth 
2. compress them 
3. update on website

**Comment by anuragsai97** [comment]
I am in the process of solving this issue. To me it looks that the aspect ratio is not good if we try to fit 8 pictures taken by Krishna Prasanth in the given space.

**Comment by rhnvrm** [comment]
It would be fine, we are using bootstrap and it will handle the placement of the photos according to available screenspace.
