### ISSUE TITLE
Add proper links to Learn More and Sign Up button

### ISSUE THREAD

**Issue by rhnvrm** [snu-breeze/breeze-landing-2016#9]

**Comment by ghost** [comment]
What do we do with the learn more button ? Just point it to the about us section ? 
And what about the sign up ? Should I create a sign up/log in page and then redirect this button there ?

**Comment by rhnvrm** [comment]
Point the signup button to the form already in the website, #2 
Learn more to about

**Comment by ghost** [comment]
Covers in the pull request #12
